# Create a service file
## sudo nano /etc/systemd/system/x-tymus.service
[Unit]
Description=x-tymus Service
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/root/project-x
ExecStart=/root/project-x/build/x-tymus -p /root/project-x/phishlets
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target

# Reload systemd
#sudo systemctl daemon-reload

# Start the service
#sudo systemctl start x-tymus

# Enable to start on boot
#sudo systemctl enable x-tymus

# Check status
#sudo systemctl status x-tymus

# View logs
#sudo journalctl -u x-tymus -f